---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-base
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2ab50166-b169-4158-9985-b88402881362
      resourcegroup: osdu-self-cpldbchg-pngy-rg
      identity: osdu-self-cpldbchg-pngy-osdu-identity
      identity_id: 24c045fb-c98a-419a-95ba-21d89463afae
      keyvault: osdu-self-cpldbc-pngy-kv
      appid: c268ca47-1767-426b-81ba-dbd3443a9f6f
    image:
      repository: osduselfcpldbcpngycr.azurecr.io
