---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-base
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2ab50166-b169-4158-9985-b88402881362
      resourcegroup: osdu-self-cplcjdej-94ld-rg
      identity: osdu-self-cplcjdej-94ld-osdu-identity
      identity_id: 8e29f039-c372-4601-a3b0-3384d6c69dbf
      keyvault: osdu-self-cplcjd-94ld-kv
      appid: 9ccfdc2c-0d44-41e8-832c-2282c07412e6
    image:
      repository: osduselfcplcjd94ldcr.azurecr.io
