---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: dev-sample
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2ab50166-b169-4158-9985-b88402881362
      resourcegroup: osdu-self-cpldbcfa-8dy5-rg
      identity: osdu-self-cpldbcfa-8dy5-osdu-identity
      identity_id: c087ec01-10c2-4a48-89c9-dba6ba804e69
      keyvault: osdu-self-cpldbc-8dy5-kv
      appid: e324a2bd-6836-46e6-a102-bca1c146645b
