---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-istio
  namespace: istio-system
spec:
  values:
    global:
      azure:
        tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
        appid: c268ca47-1767-426b-81ba-dbd3443a9f6f
