---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: self-managed-base
  namespace: osdu-azure
spec:
  values:
    fullnameOverride: osdu-svc
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2ab50166-b169-4158-9985-b88402881362
      resourcegroup: osdu-self-cplcjfdf-jprv-rg
      identity: osdu-self-cplcjfdf-jprv-osdu-identity
      identity_id: e7fb86c3-68fb-44c1-a9de-bf669a20723b
      keyvault: osdu-self-cplcjf-jprv-kv
      appid: 3c836fe6-c422-4dde-b8ea-de95c23c98d6
      oidAuthEnabled: false
    resourceLimits:
      defaultCpuRequests: "100m"
      defaultMemoryRequests: "800Mi"
      defaultCpuLimits: "1000m"
      defaultMemoryLimits: "2Gi"
    identity:
      name: osdu-identity
