name: '7.1 Load TNO Dataset (Azure/M8)'

on:
  workflow_dispatch:

env:
  CLI_VERSION: 2.30.0

  CONTROLPLANE_WORKSPACE: "cpl-${{ secrets.RAND }}"
  DATAPLANE_WORKSPACE: "dpl-${{ secrets.RAND }}"
  PARTITION_WORKSPACE: "prt-${{ secrets.RAND }}"
  DASHBOARD_WORKSPACE: "dash-${{ secrets.RAND }}"

  OSDU_VERSION: 0.11.0
  PARTITION_NAME: opendes
  IMAGE_TAG: latest

jobs:

  generate-manifests:
    name: generate-manifests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make generate-manifest executeable
        run: chmod +x ./scripts/ingestion/generate-manifest.sh
        shell: bash

      - name: Execute generate manifest
        run: ./scripts/ingestion/generate-manifest.sh
        shell: bash

  validate-manifest-generation:
    name: validate-manifest-generation
    runs-on: ubuntu-latest
    needs: generate-manifests

    steps:
      - uses: actions/checkout@v2

      - name: Make generate-manifest executeable
        run: chmod +x ./scripts/ingestion/generate-manifest.sh
        shell: bash

      - name: Execute generate manifest
        run: ./scripts/ingestion/generate-manifest.sh
        shell: bash


  generate-authcode:
    name: generate-authcode 
    runs-on: ubuntu-latest
    needs: validate-manifest-generation

    steps:
      - uses: actions/checkout@v2

      - name: Make generate-manifest executeable
        run: chmod +x ./scripts/ingestion/generate-manifest.sh
        shell: bash

      - name: Execute generate manifest
        run: ./scripts/ingestion/generate-manifest.sh
        shell: bash


  update-entitlements:
    name: update-entitlements 
    runs-on: ubuntu-latest
    needs: validate-manifest-generation

    steps:
      - uses: actions/checkout@v2

      - name: Make generate-manifest executeable
        run: chmod +x ./scripts/ingestion/generate-manifest.sh
        shell: bash

      - name: Execute generate manifest
        run: ./scripts/ingestion/generate-manifest.sh
        shell: bash    

  create-legal-tag:
    name: create-legal-tag 
    runs-on: ubuntu-latest
    needs: validate-manifest-generation

    steps:
      - uses: actions/checkout@v2

      - name: Make generate-manifest executeable
        run: chmod +x ./scripts/ingestion/generate-manifest.sh
        shell: bash

      - name: Execute generate manifest
        run: ./scripts/ingestion/generate-manifest.sh
        shell: bash      

  setup-environment-variables:
    name: setup-environment-variables 
    runs-on: ubuntu-latest
    needs: validate-manifest-generation

    steps:
      - uses: actions/checkout@v2

      - name: Make generate-manifest executeable
        run: chmod +x ./scripts/ingestion/generate-manifest.sh
        shell: bash

      - name: Execute generate manifest
        run: ./scripts/ingestion/generate-manifest.sh
        shell: bash      


  ingest-reference-master-data:
    name: ingest-reference-master-data
    runs-on: ubuntu-latest
    needs: [generate-authcode,update-entitlements,create-legal-tag,setup-environment-variables]

    steps:
      - uses: actions/checkout@v2

      - name: Make generate-manifest executeable
        run: chmod +x ./scripts/ingestion/generate-manifest.sh
        shell: bash

      - name: Execute generate manifest
        run: ./scripts/ingestion/generate-manifest.sh
        shell: bash            