name: '7.1 Load TNO Dataset (Azure/M8)'

on:
  workflow_dispatch:

env:
  CLI_VERSION: 2.30.0

  CONTROLPLANE_WORKSPACE: "cpl-${{ secrets.RAND }}"
  DATAPLANE_WORKSPACE: "dpl-${{ secrets.RAND }}"
  PARTITION_WORKSPACE: "prt-${{ secrets.RAND }}"
  DASHBOARD_WORKSPACE: "dash-${{ secrets.RAND }}"

  OSDU_VERSION: 0.11.0
  PARTITION_NAME: opendes
  IMAGE_TAG: latest

jobs:

  generate-manifests:
    name: generate-manifests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make generate-manifest executeable
        run: chmod +x ./scripts/ingestion/generate-manifest.sh
        shell: bash

      - name: Execute generate manifest
        run: ./scripts/ingestion/generate-manifest.sh
        shell: bash

  validate-manifest-generation:
    name: validate-manifest-generation
    runs-on: ubuntu-latest
    needs: generate-manifests

    steps:
      - uses: actions/checkout@v2

      - name: Make generate-manifest executeable
        run: chmod +x ./scripts/ingestion/generate-manifest.sh
        shell: bash

      - name: Execute generate manifest
        run: ./scripts/ingestion/generate-manifest.sh
        shell: bash